export const Footerselectors = {
  footer: "bg-white py-20",
  container: "container mx-auto px-4",
  topGrid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-16 mb-16 lg:justify-around  items-center",
  brandSection: "lg:col-span-2",
  brandTitle: "text-black text-3xl font-bold mb-6",
  brandDot: "text-[#2f2f2f]",
  brandDescription: "text-[#6a6a6a] text-sm leading-7 max-w-md",
  featuredContainer: "flex  justify-end gap-12 item-center  lg:col-span-3",
  columnTitle: "font-semibold text-[#2f2f2f] text-sm mb-4",
  link: "block text-[#6a6a6a] text-sm hover:text-[#2f2f2f] transition-colors",
  socialIcons: "flex items-center justify-center mb-12",
  socialImage: "w-48 h-auto hover:scale-105 transition-transform",
  divider: "border-[#6a6a6a]/20 mb-8",
  bottom: "flex flex-col md:flex-row justify-between items-center text-sm text-[#6a6a6a]",
  copyright: "mb-4 md:mb-0",
  policyLinks: "flex space-x-6 md:space-x-8",
  policyLink: "hover:text-[#2f2f2f] transition-colors font-medium",
};
